name: Build to dist branch
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v3
        with:
          node-version: '12'

      - name: Install dependencies
        run: yarn install

      - name: Build
        run: yarn build

      - name: Push to dist Branch
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: dist
          FOLDER: dist
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MESSAGE: "build({sha}): {msg}"

      - name: Push to Pages Repository
        uses: cpina/github-action-push-to-another-repository@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          source-directory: 'dist'
          destination-github-username: 'panghaibin'
          destination-repository-name: 'panghaibin'
          user-email: 'i@hbte.ch'
          target-branch: gh-pages
          target-directory: 'COVID-Risk-Region'
